### ISSUE TITLE
Installing vigrid NAS

### ISSUE THREAD

**Issue by Dilhuidy** [llevier/vigrid#1]
Hello,
I have a problem installing the vigrid NAS with git version 1.1. I'm using a virtual machine under Ubuntu 22 and I installed the NAS on VDI. But during installation, I was always confronted with a problem concerning the '/Vstorage/GNS3/vigrid/lib/systemd/system/vigrid-ZFSexportUDP.service' repository. The fact is that this repository does not exist and is not created during installation. When I go to /Vstorage/GNS3 I don't have /vigrid. I hope you'll have a solution for the proper implementation of the repository.

Respectfully

**Comment by llevier** [comment]
Hello Dilhuidy,
First of all, Welcome, you are the first to raise an issue, I was starting to wonder if someone was using Vigrid :-)

During the install process, a vigrid-update command will be created (in main, that is on line 730).
Once created, Vigrid install will launch it, thus replicating the Vigrid github to /Vstorage/GNS3/vigrid.
I feel for unknown reason this failed.
- Is '/Vstorage/GNS3/bin/vigrid-update' present ?
- Do you resolve properly github.com from the Vigrid NAS ?
- Is your PC able to directly (no proxy or proxy is configured in git) until https://github.com ?
These are the 3 conditions for the git clone to work.

Thanks for your feedback.

Brgrds

**Comment by Dilhuidy** [comment]
Hello Levier,

Thank you for your answers.

First of all, vigrid-update is installed fine, but during installation it still fails to use it.
Otherwise my VM can access github so it's not a problem.

The git clone seems to work but directory creation doesn't work.
I already had GNS3 installed when I ran the install, maybe I should let the script install it?

I have one last question, I installed vigrid in GNS3 standalone and it worked, how do I start using vigrid after installing it?

Respectfully

**Comment by llevier** [comment]
Hello Dilhuidy,

How Vigrid thinks during its install process:
- It creates a gns3 user with default values to home dir -> /home/gns3
- It creates the vigrid-update script to go into a ~gns3/bin subdirectory
- Then it launches it to replicate into ~gns3/vigrid.
By default, GNS3 behaves creating a gns3 user + doing everything into its home directory, so technically there should be no issue.

The only conflicting point I see is related to gns3 user uid:gid.
I enforce 777:777 because the first account created at Ubuntu's install takes 1000:1000.

So I suspect your gns3 account might be 1000:1000 or higher (1001 etc).
Technically this should not be a problem since I use account names rather than IDs.
BUT if your setup a Vigrid-NAS this will definitely be a problem because NFS is using IDs and not names...
"Be a problem" means you will have to take manual actions to play with configurations...or just backup your ~gns3 directory and install via Vigrid scripts...

To use Vigrid, you just launch your favorite browser and connect https to the Vigrid Master server IP/hostname.
Default page offers to dowloading gns3 heavy client + connect to the Control tower, the starting point.

Brgrds

**Comment by llevier** [comment]
1 month passed by, no answer, closing issue.
